name: Release

on:
  push:
    branches:
      - main
    paths:
      - "VERSION"

jobs:
  publish-release:
    name: Tag and publish release
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "sha=$(git rev-parse --verify --quiet HEAD^)" >> $GITHUB_OUTPUT

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          tag-template: "{VERSION}"
          version-command: |
            cat VERSION

      - name: Publish release
        id: publish-release
        uses: release-drafter/release-drafter@v6
        if: steps.check-version.outputs.tag != ''
        with:
          publish: true
          tag: ${{ steps.check-version.outputs.tag }}
          disable-autolabeler: true
          config-name: release_drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.publish-release.outputs.tag_name }}
          release-notes: ${{ steps.publish-release.outputs.body }}

      - name: Open changelog PR
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            CHANGELOG.md
          commit-message: update changelog
          title: Update changelog
          body: |
            This is an automatic pull request triggered by GitHub actions to keep `CHANGELOG.md` up to date.
          branch: update-changelog
          base: main
          labels: automated, skip-release-notes
          delete-branch: true

  # Counterintuitively, the CI workflow is triggered after the release has been published,
  # because all the images need to be built with the newly created tag.
  # TO-DO: To avoid this quirk, we should probably segregate test jobs from build jobs.
  continous-integration:
    needs:
      - publish-release
    name: Continuous Integration
    uses: ./.github/workflows/ci.yaml
