name: Release

on:
  push:
    branches:
      - main
    paths:
      - "VERSION"

jobs:
  publish-release:
    name: Tag and publish release
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "sha=$(git rev-parse --verify --quiet HEAD^)" >> $GITHUB_OUTPUT

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          tag-template: "{VERSION}"
          version-command: |
            cat VERSION

      - uses: release-drafter/release-drafter@v6
        if: steps.check-version.outputs.tag != ''
        with:
          publish: true
          tag: ${{ steps.check-version.outputs.tag }}
          disable-autolabeler: true
          config-name: release_drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # counterintuitively, we trigger this after the publishing happened,
  # because we need to build new images with the tag the previous job has just created
  continous-integration:
    needs:
      - publish-release
    name: Continuous Integration
    uses: ./.github/workflows/ci.yaml
